---
- name: enable-apache
  become: yes
  service: name=httpd enabled=yes

- name: restart-apache
  become: yes
  service: name=httpd state=restarted

- name: enable-mariadb
  become: yes
  service: name=mariadb enabled=yes

- name: restart-mariadb
  become: yes
  service: name=mariadb state=restarted
  
- name: restart-php-fpm
  become: yes
  service: name=php-fpm state=restarted

- name: enable-php-fpm
  become: yes
  service: name=php-fpm enabled=yes
