---
- name: enable workstation repos
  dnf: name=fedora-workstation-repositories state=present

- name: install chrome
  dnf: name=google-chrome-stable state=present enablerepo=google-chrome

- name: install thunderbird
  dnf: name=thunderbird state=latest

- name: install spotify
  snap: name=spotify

- name: install skype
  snap: name=skype

- name: install freecad
  snap: name=freecad
