- name: Install neovim
  become: yes
  dnf: name=neovim state=present


- name: create autoload dir
  file:
    path: ~/.local/share/nvim/site/autoload
    state: directory

- name: Check for plug
  stat: path=~/.local/share/nvim/site/autoload/plug.vim
  register: plug_dir

- name: Install plug.vim
  get_url:
      dest: ~/.local/share/nvim/site/autoload/plug.vim
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  when: not plug_dir.stat.exists

# - name: Install plug
#   become: yes
#   get_
#   command: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#   when: not plug_dir.stat.exists
