---
- name: Install development tools
  become: yes
  dnf: name='@Development tools' state=present

- name: Install Other Packages
  become: yes
  dnf:
    name:
      - autoconf
      - automake
      - pkg-config
      - cmake
      - libtool
    state: present

- name: Install docker
  become: yes
  dnf: name=docker state=latest

- name: Install docker compose
  become: yes
  dnf: name=docker-compose state=latest
